import type { BattleUpgradeDefinition } from '@openthrone/shared';
import { BattleUpgradeType } from '@openthrone/shared';

export const BattleUpgrades: BattleUpgradeDefinition[] = [
  // ─── OFFENSE ──────────────────────────────────────────────────────
  {
    type: BattleUpgradeType.OFFENSE,
    name: 'Steed',
    siegeUpgradeLevel: 0,
    level: 1,
    bonus: 200,
    cost: 100000,
    unitsCovered: 1,
    minUnitLevel: 2,
    killingStrength: 0,
    defenseStrength: 0,
  },
  {
    type: BattleUpgradeType.OFFENSE,
    name: 'War Elephant',
    siegeUpgradeLevel: 0,
    level: 2,
    bonus: 500,
    cost: 300000,
    unitsCovered: 1,
    minUnitLevel: 3,
    killingStrength: 0,
    defenseStrength: 0,
  },
  {
    type: BattleUpgradeType.OFFENSE,
    name: 'Chariot',
    siegeUpgradeLevel: 0,
    level: 3,
    bonus: 1000,
    cost: 750000,
    unitsCovered: 1,
    minUnitLevel: 4,
    killingStrength: 0,
    defenseStrength: 0,
  },

  // ─── DEFENSE ──────────────────────────────────────────────────────
  {
    type: BattleUpgradeType.DEFENSE,
    name: 'Guard Tower',
    siegeUpgradeLevel: 0,
    level: 1,
    bonus: 200,
    cost: 100000,
    unitsCovered: 1,
    minUnitLevel: 2,
    killingStrength: 0,
    defenseStrength: 0,
  },
  {
    type: BattleUpgradeType.DEFENSE,
    name: 'Catapult',
    siegeUpgradeLevel: 0,
    level: 2,
    bonus: 500,
    cost: 300000,
    unitsCovered: 1,
    minUnitLevel: 3,
    killingStrength: 0,
    defenseStrength: 0,
  },
  {
    type: BattleUpgradeType.DEFENSE,
    name: 'Trebuchet',
    siegeUpgradeLevel: 0,
    level: 3,
    bonus: 1000,
    cost: 750000,
    unitsCovered: 1,
    minUnitLevel: 4,
    killingStrength: 0,
    defenseStrength: 0,
  },

  // ─── SPY ──────────────────────────────────────────────────────────
  {
    type: BattleUpgradeType.SPY,
    name: 'Disguise Clothes',
    siegeUpgradeLevel: 0,
    level: 1,
    bonus: 200,
    cost: 100000,
    unitsCovered: 1,
    minUnitLevel: 2,
    killingStrength: 0,
    defenseStrength: 0,
  },
  {
    type: BattleUpgradeType.SPY,
    name: 'Informant',
    siegeUpgradeLevel: 0,
    level: 2,
    bonus: 500,
    cost: 300000,
    unitsCovered: 1,
    minUnitLevel: 3,
    killingStrength: 0,
    defenseStrength: 0,
  },
  {
    type: BattleUpgradeType.SPY,
    name: 'Spy Network',
    siegeUpgradeLevel: 0,
    level: 3,
    bonus: 1000,
    cost: 750000,
    unitsCovered: 1,
    minUnitLevel: 4,
    killingStrength: 0,
    defenseStrength: 0,
  },

  // ─── SENTRY ───────────────────────────────────────────────────────
  {
    type: BattleUpgradeType.SENTRY,
    name: 'Guard Dog',
    siegeUpgradeLevel: 0,
    level: 1,
    bonus: 200,
    cost: 100000,
    unitsCovered: 1,
    minUnitLevel: 2,
    killingStrength: 0,
    defenseStrength: 0,
  },
  {
    type: BattleUpgradeType.SENTRY,
    name: 'Watch Tower',
    siegeUpgradeLevel: 0,
    level: 2,
    bonus: 500,
    cost: 300000,
    unitsCovered: 1,
    minUnitLevel: 3,
    killingStrength: 0,
    defenseStrength: 0,
  },
  {
    type: BattleUpgradeType.SENTRY,
    name: 'Counter-Intel HQ',
    siegeUpgradeLevel: 0,
    level: 3,
    bonus: 1000,
    cost: 750000,
    unitsCovered: 1,
    minUnitLevel: 4,
    killingStrength: 0,
    defenseStrength: 0,
  },
];

/**
 * Returns all battle upgrade definitions of the given type.
 */
export function getBattleUpgradesByType(
  type: BattleUpgradeType,
): BattleUpgradeDefinition[] {
  return BattleUpgrades.filter((b) => b.type === type);
}
